# Generated by Django 6.0.4 on 2026-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_score_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
